### ISSUE TITLE
Installing this causes karma-babel-preprocessor to not work

### ISSUE THREAD

**Issue by MikaAK** [wilsonjackson/karma-angular-filesort#4] opened 2015-09-18 19:56 UTC
When I use this plugin with `karma-babel-preprocessor` karma throws

```
Error during loading "/Users/mika/Documents/Edvisor/jsed/client/node_modules/karma-babel-preprocessor" plugin:
  undefined is not a function
```

causing preprocessing not to work for babel.

**Comment by wilsonjackson** [comment] 2015-09-20 01:16
Do you have anything more specific, like a line number or a stack trace?

**Comment by MikaAK** [comment] 2015-09-21 18:05
I get about 10 of these, I'm using karma-cli so it auto loads the plugins. Simply uninstalling this plugin from my package.json makes this error disappear. 

```
TypeError: undefined is not a function]
TypeError: undefined is not a function
    at nextPreprocessor (/Users/mika/Documents/Edvisor/jsed/client/node_modules/karma/lib/preprocessor.js:73:28)
    at /Users/mika/Documents/Edvisor/jsed/client/node_modules/karma/lib/preprocessor.js:96:7
    at /Users/mika/Documents/Edvisor/jsed/client/node_modules/karma/node_modules/graceful-fs/graceful-fs.js:76:16
    at fs.js:334:14
    at /Users/mika/Documents/Edvisor/jsed/client/node_modules/karma/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by elmccd** [comment] 2015-10-01 21:06
I experience the same bug.

After adding this plugin, output reads:

```
WARN [plugin]: Error during loading "karma-babel-preprocessor" plugin:
  fn.call is not a function
WARN [preprocess]: Can not load "babel", it is not registered!
  Perhaps you are missing some plugin?
```

**Comment by evangalen** [comment] 2015-10-29 21:24
Fixed the bug and created a pull request for it :-)

**Comment by wilsonjackson** [comment] 2015-10-29 22:41
The fix by @evangalen is merged and published as 1.0.1. Could someone give that a try and confirm the issue is resolved?

**Comment by koshuang** [comment] 2015-11-12 16:27
My version is 1.0.4, but the error still occurs.

**Comment by evangalen** [comment] 2015-11-13 08:02
@koshuang from what I know (being merely a contributor) the latest released version is 1.0.1 (see also: https://www.npmjs.com/package/karma-angular-filesort).

Could you try again by setting the your version of "karma-angular-filesort" to "1.0.1",
then remove your "node_modules" directory, followed by a `npm cache clean` and finally a `npm install`.

Personally I tested it on 2 projects... with "1.0.1" I no longer had the issue ever since.
But as it turns out, while fixing this issue and also while developing my own custom karma preprocessors, Karma has some poor error handling... so maybe some other preprocessor is giving you a hard time.

**Comment by koshuang** [comment] 2015-11-13 08:34
Hi @evangalen,

Thanks for your help, but after I install 1.0.1, there is another error from dependent package:

```
/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:3734
            throw e;
            ^

Error: Line 33: Unexpected token )
    at throwError (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:1846:21)
    at throwUnexpected (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:1904:9)
    at parsePrimaryExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2218:13)
    at parseLeftHandSideExpressionAllowCall (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2293:61)
    at parsePostfixExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2341:16)
    at parseUnaryExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2400:20)
    at parseBinaryExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2489:16)
    at parseConditionalExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2549:16)
    at parseAssignmentExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2575:23)
    at parseExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2601:16)
    at parseGroupExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2157:16)
    at parsePrimaryExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2171:20)
    at parseLeftHandSideExpressionAllowCall (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2293:61)
    at parsePostfixExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2341:16)
    at parseUnaryExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2400:20)
    at parseBinaryExpression (/Users/kos/git/project/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/esprima/esprima.js:2489:16)
```

Do you have any idea?

**Comment by evangalen** [comment] 2015-11-13 09:55
@koshuang looking at your stack trace I think your problem isn't related to this issues nor "karma-angular-filesort"
It appears to me that you actually have a syntax error in your source-code.

**Comment by koshuang** [comment] 2015-11-13 10:06
@evangalen oh, I thought the syntax error is in the esprima package. I will check my source code.
Thank you very much!

**Comment by elmccd** [comment] 2015-11-15 13:48
1.0.1 works for me with babel. Thanks!

**Comment by wilsonjackson** [comment] 2015-11-15 19:31
Closing this, as it seems to be resolved. Thanks for your contribution @evangalen!

**Closed as completed by wilsonjackson** 2015-11-15 19:31 UTC
